name: hisp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx=0.8.0
  - matplotlib
  - pip 
  - pip:
    - git+https://github.com/remdelaportemathurin/FESTIM@f8f851303d77d04b00e1bd388e99e26774898303
    - h_transport_materials~=0.16