name: hisp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx=0.8.0
  - pip 
  - pip:
    - git+https://github.com/remdelaportemathurin/FESTIM@surface-reactions
    - h_transport_materials~=0.16
    - matplotlib