# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hisp-env
          miniforge-version: latest
          channels: conda-forge
          environment-file: environment.yml

      - name: Run example
        shell: bash -l {0}
        run: python simple_mb.py

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest test/ --cov festim --cov-report xml --cov-report term
